server:
  port: 9002
spring:
  application:
    name: ghang-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:33070/tensquare_recruit?characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true