server: 
  port: 9004
spring: 
  application:  
    name: ghang-article #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:33070/tensquare_article?characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: localhost
